### ISSUE TITLE
webpack warning on lazy-cache

### ISSUE THREAD

**Issue by elaijuh** [feathersjs-ecosystem/feathers-localstorage#60]
### Steps to reproduce

i am using it with angular 5, when webpack compiling the source code, it shows errors
 

### Actual behavior
```
WARNING in ./node_modules/shallow-clone/utils.js
3:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

the `lazy-loader` webpack loader might solve this problem, but it's worthy to mention this flaw in read me

**Comment by daffl** [comment]
Do you know what it expects for the `require`? Does it work when including `dist/feathers-localstorage` instead?

**Comment by elaijuh** [comment]
I haven't look deep into it yet

**Comment by daffl** [comment]
I think this should be fixed with the Webpack 4 build or the distirbutable.
