### ISSUE TITLE
Use with create-react-app

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs-ecosystem/feathers-localstorage#66]
### Steps to reproduce

Using [create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) with this module breaks the build.

I'm using `@feathers/client` rather than `@feathers/feathers` and, when I exclude this module, everything builds. With it, the build breaks.

### Expected behavior
The create-react-app build should not break.

### Actual behavior
It does break. :-P

![image](https://user-images.githubusercontent.com/2819256/38755653-67d440da-3f1b-11e8-80f7-e25517d48972.png)

It seems to have the same error as using `@feathers/feathers` does, ie something in `@feathers/commons`.

**Comment by daffl** [comment]
With create-react-app, use the ES5 build from `feathers-localstorage/dist/feathers-localstorage` instead.

**Comment by saiichihashimoto** [comment]
![image](https://user-images.githubusercontent.com/2819256/38758148-7e57d73c-3f24-11e8-9994-00a49fa37088.png)

![image](https://user-images.githubusercontent.com/2819256/38758137-765fc4ea-3f24-11e8-8a8c-022d40ab0f52.png)

Doesn't really change much...

**Comment by daffl** [comment]
Well shoot, looks like some ES6 modules slipped through the transpilation step. Give it another go with the latest version 2.0.2
