### ISSUE TITLE
feathers-localstorage@4.0.0 throw an error on trying execute service.find() method

### ISSUE THREAD

**Issue by everton-e26** [feathersjs-ecosystem/feathers-localstorage#85]
### Steps to reproduce

Create a project with `react-native init MyApp` using @feathersjs/feathers@3.3.1 and feathers-localstorage@4.0.0 installed and run the following code with Debug JS Remotely option **disable** (curiously with this option enabled works)

```
import React, { Component } from "react";
import { Platform, Text, View, AsyncStorage } from "react-native";
import feathers from "@feathersjs/feathers";
import localstorage from "feathers-localstorage";

export default class App extends Component {

  componentDidMount() {
    const app = feathers().use(
      "/messages",
      localstorage({ storage: AsyncStorage })
    );

    const messages = app.service("messages");

    //here throws an error
    messages
        .find()
        .then(result => console.warn("find", result))
        .catch(err => console.warn("err", err));
  }

  render(){
     return <View />
  }

}
```

### Expected behavior

the find method should return a array with the localstorage data

### Actual behavior

throw unexpected error without more information

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

```
"dependencies": {
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/socketio-client": "^1.2.1",
    "feathers-localstorage": "^4.0.0",
    "react": "16.6.3",
    "react-native": "0.58.6",
    "socket.io-client": "^2.2.0"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.53.0",
    "react-test-renderer": "16.6.3"
  }
```

**NodeJS version**:

v10.15.1

**Operating System**:

Mac Os 10.14.3

**Browser Version**:

**React Native Version**:

0.58.6

**Module Loader**:

**Comment by daffl** [comment]
Something like `.catch(err => console.warn(err.stack));` should at least give more information of where the error is coming from.
