### ISSUE TITLE
offline first mobile (advice)

### ISSUE THREAD

**Issue by bilicio** [feathersjs-ecosystem/feathers-localstorage#86]
Hi @daffl !

Im using feathersjs in all my projects, thank you for this amazing framework 👍 . 
Im now looking for some solutions on mobile to keep database sync when offline devices become online.  When you have time, can you advice me how to achieve this with feathers? 
is there any way to seamless make the calls on client and if it become offline it save local and when online the data syncs?
I achieve this with gun but if i make a simple mistake on saving data the database can corrupt easely. 
I tryed with meteor too but i like too much feathers to change it to another backend soution.

Thank you!!

**Comment by laurensiusadi** [comment]
Agree @bilicio I'm also interested to know more about this.
There's this repo https://github.com/feathers-plus/feathers-offline-realtime
Haven't tried it.
